package org.example.jpastudent.controller;

import org.example.jpastudent.model.Student;
import org.example.jpastudent.repositories.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

@RestController
public class StudentRestController {
  @Autowired
   StudentRepository studentRepository;
    @GetMapping("/students")
    public List<Student> students(){
        return studentRepository.findAll();

    }
    @GetMapping("/addstudent")
    public List<Student> addstudent(){
        Student std = new Student();
        std.setBornTime(LocalTime.now());
        std.setBornDate(LocalDate.now());
        List<Student> lst = studentRepository.findAll();
        std.setName("Autogenerated sz =" + lst.size());
        studentRepository.save(std);

        return studentRepository.findAll();
    }
    @GetMapping("students/{name}")
    public List<Student> getAllStudentsByName(@PathVariable String name){
        return studentRepository.findAllByName(name);
    }
}
